* Introduction
** High throughput data collection has enabled new kinds of biological discovery, to the point where computational power becomes a limiting factor. As the price and acquisition time for genomic data continues to fall, these computational limits will only become a bigger drag/bottleneck on scientific progress.
** Succinct data structures and accompanying algorithms offer increased efficiency which have staved off some encumberance of this problem.  
** In this work we present our findings and propose novel exploration of sophisticated applications of succinct data structures to further develope their utility.
** We demonstrate we can increase the reach of prior methods with sophisticated applications of succinct data structures by reducing runtime or memory footprint.
** The enhanced scalability can translate to higher quality of results with a given set of computational resources.



* Background
** Succinct data structures increase CPU efficiency through indexing capacity
** Succinct data structures increase memory efficiency through compression.




* unsorted
** PFGE
** no core genome, predicted k-mer count
