* strain typing
Rapid Whole-Genome Sequencing for Surveillance of Salmonella enterica Serovar Enteritidis
Emerg Infect Dis. 2014 Aug; 20(8): 1306–1314.
doi:  10.3201/eid2008.131399
PMCID: PMC4111163
Henk C. den Bakker, Marc W. Allard, Dianna Bopp, Eric W. Brown, John Fontana, Zamin Iqbal, Aristea Kinney, Ronald Limberger, Kimberlee A. Musser, Matthew Shudt, Errol Strain, Martin Wiedmann, and William J. Wolfgangcorresponding author
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4111163/
(talks about PFGE inaccuracy)


http://jcm.asm.org/content/53/1/212.full
Comparative Analysis of Subtyping Methods against a Whole-Genome-Sequencing Standard for Salmonella enterica Serotype Enteritidis
Xiangyu Denga, Nikki Shariatb, Elizabeth M. Driebec, Chandler C. Roec, Beth Tolard, Eija Treesd, Paul Keimc,e, Wei Zhangf, Edward G. Dudleyb,g, Patricia I. Fieldsd and David M. Engelthalerc




* colored graphs: 
splitmem 2014
twopaco 2016
pantools 2016
bloom filter trie 2016

Juha Kärkkäinen, Dominik Kempa, Simon J. Puglisi, Bella Zhukova: Engineering External Memory Induced Suffix Sorting. ALENEX 2017: 98-108

Juha Kärkkäinen, Dominik Kempa, Simon J. Puglisi: Parallel External Memory Suffix Sorting. CPM 2015: 329-342

** SplitMEM: 

*** improves over splitMEM construction by means of compressed suffix tree+BWT
Graphical pan-genome analysis with compressed suffix trees and the Burrows–Wheeler transform 
Uwe Baier  Timo Beller  Enno Ohlebusch
https://academic.oup.com/bioinformatics/article-lookup/doi/10.1093/bioinformatics/btv603
**** same as: Beller T. Ohlebusch E. ( 2015 ). Efficient construction of a compressed de Bruijn graph for pan-genome analysis . In: Lecture Notes in Computer Science  , volume 9133 , Springer Verlag , Berlin, Germany , pp. 40 – 51 .

**** "Unfortunately, both tools use more memory than the original size of the input sequences." bloom filter trie


** TwoPaCo: an efficient algorithm to build the compacted de Bruijn graph from many complete genomes
https://academic.oup.com/bioinformatics/article-abstract/doi/10.1093/bioinformatics/btw609/2725383/TwoPaCo-an-efficient-algorithm-to-build-the



** PanTools
*** only small datasets demonstrated (19 arabidopsis)

** MuGI: Indexes of Large Genome Collections on a PC
Agnieszka Danek,  Sebastian Deorowicz,  Szymon Grabowski PLOS x
Published: October 7, 2014 https://doi.org/10.1371/journal.pone.0109384
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0109384
*** talks about merging, works on genomes, not graphs, does read mapping

** Bloom Filter Trie


* tangentially related

** A Four-Stage Algorithm for Updating a Burrows-Wheeler Transform
M. Salsona,1, T. Lecroqa , M. L´eonarda , L. Moucharda,b,∗
https://pdfs.semanticscholar.org/ed92/4cb7c2f7c6be5f827afc317d62d660f1289c.pdf


** BCALM 2: Compacting de Bruijn graphs from sequencing data quickly and in low memory
Rayan Chikhi1,*, Antoine Limasset2 and Paul Medvedev 3,4,5
https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformatics/32/12/10.1093_bioinformatics_btw279/1/btw279.pdf?Expires=1496345438&Signature=PBzGgULnYIou3Gu1AcQ8xnfLD5jH8l2-qH4WKNYcgoLGRhOqayQeZhX2abkUuZi9S3PA61tr6B950keoQ4i38UZTVpswDhUF~IU8D9Z-AmNiyZ~kBKFaNxIyigyKGGjbKa8Bt5ewmgpS-x5hI62FotfDbAu37X107vrnqNHHvIkl65lsr2a9i6mCzsKaafs7hBgcxloP7Id-qJaphmpztihQF6Az-ZQWMw1X3pGq2cbNzDrt~PbyV2WjqcjkLp-a2A5wnPeJwZvOAK8bzme7cY4h2SJWh8nfAFO37gA-K~N-kOCGKCqsYhi95kQAHpnpoQAi7l3FodxcL0JKpBJLJQ__&Key-Pair-Id=APKAIUCZBIA4LVPAVW3Q



** Juha Kärkkäinen, Dominik Kempa, Simon J. Puglisi, Bella Zhukova: Engineering External Memory Induced Suffix Sorting. ALENEX 2017: 98-108

** Juha Kärkkäinen, Dominik Kempa, Simon J. Puglisi: Parallel External Memory Suffix Sorting. CPM 2015: 329-342

** That paper Zam mentioned on twitter that builds on vari and has a (bio)arxiv paper


https://www.researchgate.net/publication/309720482_Computational_pan-genomics_status_promises_and_challenges
same as
https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bib/PAP/10.1093_bib_bbw089/2/bbw089.pdf?Expires=1500518017&Signature=Z2fiHWeslN1wvi8nqFNP-NlXwxWJa~9hJCiDvGErMhI-b2TMIUgX~X-U7Ctnk7mukwX8zG74RxIKOyFnQnIMebP1W0LCZENCl9BgVL4u1hPhJJxzBNO9me~NQcUdicXT0LX5R0iOLE7lfQ6zDs1V~K5N27y41lOZpOv~R7i-TSGtq1Z8tO4Qp~XriWJo71WbGzT8A6pZn9d1GXTg~6S1mpM8D1gH6w3yEBgtlQxo9yyW3AiOoSF61QtBEyB8q8Av8YsNqFd8Ku5Vn9R9yzg6OpCqBkBDyfNW32xag3f1Yi6p-zppCoeUuH04vHd1~~ofEbXeXiM1FS0r5pDfaoneNQ__&Key-Pair-Id=APKAIUCZBIA4LVPAVW3Q
