


* important (introduction)
** lots of data helps science
** too much data
** compressed data structures are small
** compressed data structures have efficient lookup
** BWT
** FM-Index
** graph traversal, random access, giant RAM machines
** optical map info
** comparative genomics
** shotgun data and assembly
** aspects of succint data structures: construction, modeling, navigation

What else do people need to know? There will be a hierarchy of introductions.  
* background (semantically part of introduction)

* specific: 
** enhance vari, 
** run on genometrakr, 
** selective bubble call, 
** featurize bubbles
** compare to k-mer approach for predicting metadata from sample
** Though it is well known that evolution progresses in ways beyond SNPs, such that graph approaches are required, it is unclear whether including features derived from exposing those variations offers better specificity.  In this work, we propose doing the first measurements, however also make the data available such that data science specialists have the opportunity to further explore the utility of these features.

* (novel) state of the art/prior work
** have state of art colored dBG
** state of art surveilance 
** state of art on genometrakr

* viable (preliminary results)
** stats on assembly process
** progress on code revision
** 

** timeline

* conclusion
** future work



* unsorted
** for sequence analysis, we're interested in where they match and where they differ, or how to build sequences and then how to compare them.

** problems with low quality samples, can't assemble well
** bart mentioned some problems, like adaptor contamination

I'm out of ideas, these things answer the main point.  where do I go from here?

where do I put research exam stuff?

intro should forward reference sections

how do I organize planned and completed work?  C says to list it as preliminary.
People are looking for a proposal. Other students have presented their past work as preliminary results toward a big problem that uses them.  I guess I present this as enough work in the context of a PhD?  That is part of the problem, how do you define a SMART goal?


the problem is there are two competing organization strategies, one as a proposal, one as a body of work.  I think it should go as a proposal.  It will be easier to understand.

How should I order TWIN/misSEQuel/KOHDISTA?  TWIN/misSEQuel should be combined, KOHDISTA should come later.  Is this where we discuss assembly?  Maybe we need to understand assembly first.
